### ISSUE TITLE
Nedmalloc crashes on android

### ISSUE THREAD

**Issue by wolfpld** [ned14/nedmalloc#10]
I'm using nedmalloc git master's branch head (c8a6ed9510377d439b02dc6e15b26952da294e94) in my application. Android build have a 100% repro for crash in allocator when I'm restoring my application from background. The stack stace is as follows:

Program received signal SIGBUS, Bus error.
[Switching to Thread 5318]
0x684dfbf0 in mmap_alloc (m=0x68689008, nb=553120, flags=0) at jni/../../../contrib/nedmalloc/malloc.c.h:4094
4094          _(void_*)mm = mmaph;
(gdb) bt
0  0x684dfbf0 in mmap_alloc (m=0x68689008, nb=553120, flags=0) at jni/../../../contrib/nedmalloc/malloc.c.h:4094
1  0x684df52c in sys_alloc (m=0x68689008, nb=553120, flags=0) at jni/../../../contrib/nedmalloc/malloc.c.h:4302
2  0x684ccff4 in mspace_malloc_implementation (ms=<optimized out>, bytes=<optimized out>, flags=<optimized out>, ms=<optimized out>, bytes=<optimized out>, flags=<optimized out>) at jni/../../../contrib/nedmalloc/malloc.c.h:5577
3  mspace_malloc2 (msp=0x68689008, bytes=553108, alignment=0, flags=0) at jni/../../../contrib/nedmalloc/malloc.c.h:5602
4  0x684d6c84 in GetMSpace (p=0x686b7c78, tc=<unknown type in C:\Users\wolf\Desktop\DarkRL\build\android/./obj/local/armeabi-v7a/libDarkRL.so, CU 0x0, DIE 0x67b1>, mymspace=0, size=553108, mspace=<unknown type in C:\Users\wolf\Desktop\DarkRL\build\android/./obj/local/armeabi-v7a/libDarkRL.so, CU 0x0, DIE 0x67d5>, size=553108, alignment=0, flags=0, sl=0x0) at
jni/../../../contrib/nedmalloc/nedmalloc.cpp:355
5  nedalloc::nedpmalloc2 (p=0x686814c0, size=553108, alignment=0, flags=0) at jni/../../../contrib/nedmalloc/nedmalloc.cpp:1960
6  0x684d64c8 in nedalloc::nedpmalloc (p=0x0, size=553108) at jni/../../../contrib/nedmalloc/nedmalloc.cpp:2069
7  0x684d6478 in nedalloc::nedmalloc (size=553108) at jni/../../../contrib/nedmalloc/nedmalloc.cpp:668
8  0x684e1194 in MemAlloc (size=553104) at jni/../../../src/Alloc.cpp:33
9  0x684e14c8 in operator new[](size=553104) at jni/../../../src/Alloc.cpp:94
10 0x685934ec in VideoAndroid::InitDataBuffer (this=0x68691414) at jni/../../../src/videoandroid/VideoAndroid.cpp:620
11 0x68593004 in VideoAndroid::StartGL (this=0x68691414) at jni/../../../src/videoandroid/VideoAndroid.cpp:363
12 0x68594fe4 in Java_com_darkrl_darkrl_DarkRenderer_nativeStartGL (env=0x64e37b60) at jni/../../../src/videoandroid/VideoAndroid.cpp:635
13 0x4074be34 in ?? ()
14 0x4074be34 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

The issue seems to be very similar to
https://github.com/ned14/nedmalloc/issues/3

Tested compilation settings combinations:

clang-3.1 armeabi-v7a debug     CRASH
clang-3.1 armeabi-v7a release   CRASH
clang-3.1 armeabi     debug     CRASH
gcc-4.7   armeabi-v7a debug     CRASH

**Comment by ned14** [comment]
Thankfully that bug was easy! For some reason I had thought mmap() returns 0 on failure, rather than (size_t)-1. It was very obvious when I looked at it.

Bad news for you though is that your memory allocation is failing on process restore for some reason.

Thanks for the bug report.

Niall
