### ISSUE TITLE
vc++8.0 support 

### ISSUE THREAD

**Issue by surusara** [ned14/nedmalloc#13]
Hi,
I have one old application written for trade processing. Due high volumne now days performing very slow. I am working for one big bank back office. 
I have seen nedalloac , tested in vc++ 9.0 looks good. 
I want to implement this in my project. It is giving so many error when I am trying to compile this in vc++ 8.0 ( visual studio 6.0).
Is there any way to use this in VS 6.0.
I tried converting my apps to vc++ 9.0, but there also so many errors.
Can u please help me to implement this in vC++ 6.0.
Error is in winnt.h , few constant are not defined in winntt.h of VS6.0 where as defined in VC ++ 9.0.
jaiswal.surendra@ gmail.com

**Comment by ned14** [comment]
This forum is for reporting bugs, not asking for support. I'll get to replying to the comments you left on the project's page at the weekend or when I next get free time.
