### ISSUE TITLE
Compilation issue on old systems

### ISSUE THREAD

**Issue by Gerilgfx** [ned14/nedmalloc#17]
Compilation issue on old linux systems:

nedmalloc cannot compiled on older systems (like suse 10.1). old pthreads have a bit different names for some mutex functionality. for example:

undefined reference to `pthread_mutexattr_setkind_np(pthread_mutexattr_t*, int)'

solution: better pthread version detection.

**Comment by ned14** [comment]
Never been asked for this before in eight years of history.

I don't have access to any such systems - I'm actually intending to migrate my oldest systems which are Ubuntu 10.04 based to 14.04 this year, so I'll be losing 10.04 soon. A patch would be welcome.
