### ISSUE TITLE
Make C++0x support optional?

### ISSUE THREAD

**Issue by xgalaxy** [ned14/nedmalloc#4]
Hello,

Would it be possible to make C++0x optional? I was using nedmalloc from November of last year just fine, but with the latest stuff it forces C++0x in the SConscript which I do not want to use.

Also, the change added env['LIB'] = ["rt"] which is also causing errors. I'm running OSX with GCC / Xcode 3.

These changes were made here:
https://github.com/ned14/nedmalloc/commit/e4db14b85e65643a270536a28eaaacdd19c92675#SConscript

**Comment by ned14** [comment]
Good catch - I had forgotten about BSD differences. It's inexcusable actually as I have a BSD box upstairs.

Regarding librt, it's necessary for the timing routines in the test framework. I think these live in libc on Mac? I'll add a build time test to discover these and link properly.

Would you be okay if it tests at build time for C++0x features and turns them on only if available?

**Comment by xgalaxy** [comment]
Yes that would be fine.

Thanks for the quick reply!

**Comment by ned14** [comment]
Try https://github.com/ned14/nedmalloc/commit/51ab2a2ab194aa81e6a76d8d688fbe77b9d3eb3e and let me know how it goes for you. Works fine on FreeBSD, but I don't have access to a Mac right now.
