### ISSUE TITLE
Crash when nedcreatepool is called in the fifth time.

### ISSUE THREAD

**Issue by mxmauro** [ned14/nedmalloc#7]
Hi,

I'm implementing a memory pool similar to the one used in this url:

http://gmogre3d.googlecode.com/svn-history/r815/trunk/OgreMain/src/OgreMemoryNedPooling.cpp

When nedcreatepool is called in the fifth time (poollist->length=poollist->size=5), crash occurs in ok_magic test in mspace_realloc2 function.

I used this settings in nedmalloc.h
# define USE_ALLOCATOR              1
# define MSPACES                    1
# define ONLY_MSPACES               1
# define USE_LOCKS                  1
# define FOOTERS                    1
# undef REPLACE_SYSTEM_ALLOCATOR
# undef ENABLE_LOGGING
# define MAX_RELEASE_CHECK_RATE   255
# define USE_MAGIC_HEADERS          1
# define ENABLE_FAST_HEAP_DETECTION 1
# define REALLOC_ZERO_BYTES_FREES   1
# ifdef _DEBUG

  #define NEDMALLOC_DEBUG          1
  #define DEBUG                    1
# else

  #undef DEBUG
# endif //_DEBUG

and nedmalloc.c is compiled as c++.

As I see, the mstate fm = get_mstate_for(p); is not working fine because the prev_foot variable is zero and, when xored with mparams.magic it gives us a bad pointer.

Regards,
Mauro.

**Comment by mxmauro** [comment]
I think I found a fix. I replaced some of the code. The original is between comment tags and below mine's.

I don't know if the problem belongs to nedpcalloc that zeroes memory or to the memset that zeroes the poollist variable when relocated.

Regards,
Mauro.

<code>
/*
    if(!poollist)
    {
        PoolList _newpoollist=0;
        if(!(newpoollist=(PoolList *) nedpcalloc(0, 1, sizeof(PoolList)+sizeof(nedpool *)))) return 0;
#if USE_LOCKS
        INITIAL_LOCK(&poollistlock);
        ACQUIRE_LOCK(&poollistlock);
#endif
        poollist=newpoollist;
        poollist->size=sizeof(poollist->list)/sizeof(nedpool *);
    }
#if USE_LOCKS
    else
        ACQUIRE_LOCK(&poollistlock);
#endif
    if(poollist->length==poollist->size)
    {
        PoolList *newpoollist=0;
        size_t newsize=0;
        newsize=sizeof(PoolList)+(poollist->size+1)_sizeof(nedpool *);
        if(!(newpoollist=(PoolList *) nedprealloc(0, poollist, newsize))) goto badexit;
        poollist=newpoollist;
        memset(&poollist->list[poollist->size], 0, newsize-((size_t)&poollist->list[poollist->size]-(size_t)&poollist->list[0]));
        poollist->size=((newsize-((char *)&poollist->list[0]-(char *)poollist))/sizeof(nedpool *))-1;
        assert(poollist->size>poollist->length);
    }
    if(!(ret=(nedpool *) nedpcalloc(0, 1, sizeof(nedpool)))) goto badexit;
  */
  if(!poollist)
  {
    PoolList *newpoollist=0;
    if(!(newpoollist=(PoolList *) nedpmalloc(0, sizeof(PoolList)))) return 0;
    memset(newpoollist, 0, sizeof(PoolList));
#if USE_LOCKS
    INITIAL_LOCK(&poollistlock);
    ACQUIRE_LOCK(&poollistlock);
#endif
    poollist=newpoollist;
    poollist->size=sizeof(poollist->list)/sizeof(nedpool *);
  }
#if USE_LOCKS
  else
  {
    ACQUIRE_LOCK(&poollistlock);
  }
#endif
  if(poollist->length==poollist->size)
  {
    PoolList *newpoollist;
    size_t newsize;

```
newsize=sizeof(PoolList)+(poollist->size+1)*sizeof(nedpool *);
if(!(newpoollist=(PoolList *) nedprealloc(0, poollist, newsize))) goto badexit;
poollist = newpoollist;
poollist->list[poollist->size] = NULL;
poollist->size++;
assert(poollist->size > poollist->length);
```

  }

  if(!(ret=(nedpool *) nedpmalloc(0, sizeof(nedpool)))) goto badexit;
  memset(ret, 0, sizeof(nedpool));
</code>

**Comment by ned14** [comment]
I'm surprised there's a bug here in my original version, but I agree we could do with a unit test for this particular problem. I'll try to get onto it next weekend (20th-21st Oct).

Thanks for the bug report.

Niall

**Comment by mxmauro** [comment]
Hi Niall,

Thanks to you for the great piece of code.

Two extra thing I noticed (you can add as a test but they may not be bugs, may be only one mistake from me):

When using more than one pool, if I forget in one thread to call the neddisablethreadcache, after some time I get a crash in tcsanitycheck because bad pointers.

Also, in when using the library in a dll, and dllmain is called with DLL_PROCESS_DETACH and lpReserved == NULL (because of a freelibrary call) I first call neddisablethreadcache on all pools (including the syspool), then neddestroypool  (for the custom pools) and at last neddestroysyspool. If I don't follow that order I may receive a crash again in tcsanitycheck.

(My o.s. is Win7 x64 but the tests were done in x86 apps)

Regards,
Mauro.

**Comment by ned14** [comment]
Fixed the bug. Thanks for reporting it.

Regarding not calling neddisablethreadcache() causing crashes, try it now. The bug was a memory corruption bug and could have had all sorts of indirect consequences.

Regarding using the library in a dll, look at nedmalloc's own DllMain() for what to do when DLL_PROCESS_DETACH occurs. Do bear in mind you don't need to disable a thread's thread cache for a pool if you're about to delete that pool.

Thanks once again for the bug report.

Niall
