### ISSUE TITLE
possible bug when allocating freeing memory blocks allocated rapidly with nedindependent_comalloc

### ISSUE THREAD

**Issue by Gerilgfx** [ned14/nedmalloc#8]
bug report: possible bug when allocating freeing memory blocks allocated rapidly with nedindependent_comalloc
affects: memory corruption, nedmalloc internal error, or application crash
version: newest

bug possible rating: critical

header setup:
    #define USE_LOCKS 1
    #define USE_DL_PREFIX 1
    #define NDEBUG
    #define NO_NED_NAMESPACE
    #define INSECURE 1

testcase:

```
void MallocStabTest(){
    printf("test\n");
    void ** test=(void**)nedmalloc(1024*1024*16*sizeof(void**));
    for(int i=0;i<(1024*1024*16);i++) test[i]=NULL;
    for(int j=0;j<10000000;j++){
        int testbyte=rand()%((1024*1024*16)-128);

        for(int w=0;w<127;w++){
            if(test[testbyte+w]){
                nedfree(test[testbyte+w]);
                test[testbyte+w]=NULL;
            }
        }

        test[testbyte++]=nedmalloc(10);
        test[testbyte++]=nedmalloc(40);
        test[testbyte++]=nedmalloc(100);

        test[testbyte+2]=nedmalloc(100);
        test[testbyte+1]=nedmalloc(40);
        test[testbyte]=nedmalloc(7);

        testbyte+=3;

        void * mallblocks[7];
        size_t mallsz[7]={10,20,30,40,50,60,70};
        nedindependent_comalloc(7, mallsz, mallblocks);

        test[testbyte++]=mallblocks[0];
        test[testbyte++]=mallblocks[6];
        test[testbyte++]=mallblocks[2];
        test[testbyte++]=mallblocks[5];
        test[testbyte++]=mallblocks[4];
        test[testbyte++]=mallblocks[3];
        test[testbyte++]=mallblocks[1];

    }
    for(int i=0;i<(1024*1024*16);i++) if(test[i]) nedfree(test[i]);
    nedfree(test);
    printf("end\n");
}
```

compiler version:

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.6/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.6 --enable-ssp --disable-libssp --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.6 --enable-linux-futex --without-system-libunwind --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.6.2 (SUSE Linux)

settings:
-O3 -s -ftree-vectorize -ffast-math -mrecip -momit-leaf-frame-pointer

output:
nedmalloc: nedpfree() called with a block not created by nedmalloc!

other parameters:

both 32 and 64 bit mode affected

**Comment by Gerilgfx** [comment]
the version v1.10 beta 3 fails too

**Comment by ned14** [comment]
Thanks for the bug report. There was a memory corruption bug fixed in issue #7, but I'd very much doubt that's in play here. I'd assume it's a different memory corruption bug :(

I'll try to get onto it this weekend sometime.

Niall

**Comment by Gerilgfx** [comment]
thankyou. another interesting thing is that using comalloc is actually slower, than mallocs. maybe its a compilation issue with gcc. i will check it with windows today afternoon. if i remember good, the bug was not exist there.

**Comment by ned14** [comment]
Runs fine on MSVC x86 on my Atom laptop :) But that's not unsurprising. I'll try it on a remote Linux box tomorrow.

**Comment by Gerilgfx** [comment]
I have tryed it on Windows too, it runs fine (mingw32, some ~2010 version included in ~2010 version of codeblocks).

**Comment by ned14** [comment]
As I mentioned, it's not unsurprising it works on Windows but not Linux. Each can hide memory corruption differently. It does suggest, however, that it may be tricky to nail down. But I'll give it a try anyway. I have some very old code which patches nedmalloc into valgrind, and then valgrind tracks the memory corruption for you. Might dig that out.

**Comment by Gerilgfx** [comment]
okay. if necessary, and the bug does not happens for you, i create an SSH access to my computer. do you have skype, or msn, or whatever?

**Comment by ned14** [comment]
Some trial & error results:

Disabling the threadcache (#define THREADCACHEMAX 0) and the abort goes away.

OR

Replacing nedindependent_comalloc() with a near equivalent set of mallocs and the abort goes away.

```
#if 0
        nedindependent_comalloc(7, mallsz, mallblocks);
#else
mallblocks[0]=nedmalloc(10);
mallblocks[1]=nedmalloc(20);
mallblocks[2]=nedmalloc(30);
mallblocks[3]=nedmalloc(40);
mallblocks[4]=nedmalloc(50);
mallblocks[5]=nedmalloc(60);
mallblocks[6]=nedmalloc(70);
#endif
```

There is obviously something about the way in which nedindependent_comalloc() returns blocks allocated back to back which is showing up a memory corruption by the threadcache. Or something is up with comalloc, yet if the threadcache is off nothing turns up.

Unfortunately I don't have comalloc ported to work with valgrind yet. Perhaps the time has come ...

Niall

**Comment by ned14** [comment]
valgrind found no corruption when running with nedmalloc in system allocator using mode. Of course, in that mode independent_comalloc is emulated. It's definitely something to do with independent_comalloc.

Just tried merging dlmalloc v2.8.6 in case it was a memory corruption bug in v2.8.4 as v2.8.6 fixed a miscalculated when claiming system memory. Turns out no change.

Fraid I'm out of time this weekend. I'll try to find some hours next weekend. dlmalloc v2.8.6 comes with a ton of new features which lets me greatly simplify nedmalloc. It may just happen that that fixes the problem.

**Comment by Gerilgfx** [comment]
when i replace the abort in nedmalloc to return, the software suprisingly continues to work, it circles the error for a few seconds, then the error is gone, and the app runs without crash, so it seems the memory is allocated.

maybe comalloc forgots to add a chunk somewhere?

**Comment by ned14** [comment]
Finally figured it out ... the logic for disambiguating ptmalloc and dlmalloc blocks is tricky to keep fast, so I use a low water mark pointer to speed things up. The independent_*() functions weren't lowering that pointer, so the system block identification routine was incorrectly thinking the block was from the system. Fixed now. And thanks for the bug report.
